# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb848a02ba72c9775ccff9fdfbb532dbaa0dda08919256229a7f8f8c391a4135279b4dd6b99b63eaa5560b85c36532cee5746a864ce1ea8db99da9acb192618

test:
  secret_key_base: 7ffd9c4c742f7167060fcad8e26811837b9fe54bd738e10095161bae411a321900a397f91b8e8cb9f810c943c4c7c7ecf422d789bbcc8218686f9ffad0ab5f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
